### ISSUE TITLE
这个要搭配biliTickerBuy使用？

### ISSUE THREAD

**Issue by tiandao716** [Amorter/biliTicker_gt#11]
能不能单独运行，通过127.0.0.1接受gt chall再返回va

在biliTickerBuy进行本地验证码是可以正常输出gt chall跟返回va

**Comment by Amorter** [comment]
当然可以，不过你要用127.0.0.1这样的话要自己写api

**Comment by tiandao716** [comment]
> 当然可以，不过你要用127.0.0.1这样的话要自己写api

好的，我去折腾折腾。谢谢d
