### ISSUE TITLE
头一次遇到的错误，try了都被强制关闭了

### ISSUE THREAD

**Issue by jack68CN** [Amorter/biliTicker_gt#15]
```
thread '<unnamed>' panicked at src\click.rs:284:47:
未知错误
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
key = click.calculate_key(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: 未知错误
```

**Comment by Amorter** [comment]
居然是算法的问题，你有测试的图片吗，我需要复现

**Comment by jack68CN** [comment]
我还真找到了challenge =  72c01df4139d27a5b59272822540bddc
我在编译器里跑的，目前窗口没关，还需要在哪找点什么数据？我尽量帮忙

**Comment by Amorter** [comment]
![image](https://github.com/Amorter/biliTicker_gt/assets/63935225/8c2ed9e8-76a0-46cb-8059-b1e60664c171)
这个args是问题的图片链接，我需要这个

**Comment by jack68CN** [comment]
"pic": "/captcha_v3/batch/v3/75028/2024-07-01T17/word/0bcf1b437373471f9c45d607063e00d0.jpg"

**Comment by Amorter** [comment]
好的，我这边分析一下

**Comment by Amorter** [comment]
下个版本解决
