### ISSUE TITLE
求视频教程

### ISSUE THREAD

**Issue by Llyjus** [Amorter/biliTicker_gt#20]
可以上传视频教程吗 跪求qwq

**Comment by Amorter** [comment]
什么教程，可是这个是库呀，不是应用，需要教什么呢

**Comment by Llyjus** [comment]
解压后应该怎么做呀，直接打开cmd输入指令会对pip报错哎

**Comment by Amorter** [comment]
> 解压后应该怎么做呀，直接打开cmd输入指令会对pip报错哎

不需要clone源代码，直接使用pip install即可

**Comment by Llyjus** [comment]
噢噢只是开源了是吧，懂了，谢谢！
